.TH HISTW 7 "v\ R2-41-g732c471" "Wed, June 29, 2011" "DARWIN\ \-\ MAC\ OS\ X"
.SH NAME
.B histw
\- Advances to the next episode in Safari
.SH SYNOPSIS
histw
.br
.SH DESCRIPTION
Advances to the next episode in Safari, 
.B histwc 
uses Camino
.br
.SH VERSION
This documentation describes
.B histw
version 2-41-g732c471
.SH AUTHOR
.br
.B Bilal Hussain
.br