.TH histm 7 "R249" "Thr, December 30, 2010" 
.SH NAME
.B histm 
\- adds/updates a series history using data from ongoing
.SH SYNOPSIS
histm
.br

.SH DESCRIPTION
histm adds/updates a series watching history. 
.br

.SH AUGMENTS 
.B Series
\- chosen from the list of series 

.B All other args all optional (lower_num is the current ep +1 by default)

.B lower_num
\- The episode to update 

.B time 
\- The time at which the episode was watched e.g
.br
	2 days ago
.br
	2008-01-23 at 3pm
.br
	23 mins ago
.br 
	7 days ago at 2:21
.br

.B upper_num
\- The number to update to 

.B sep
\- The time between the start of the start of two episode in minutes default 27 minutes. 

.B score 
\- The rating of the series from 1 to 10

.B t 
\- Prints the choices made 

.SH SEE ALSO 
media(7), mal(7), hista(7), nums(7), ongoing(7), shash(7)


.SH BUGS
None yet
.SH VERSION
This documentation describes
.B histm
version 249
.br
.SH AUTHOR
.br
.B Bilal Hussain
.br
