.TH nums 7 "R200" "Tue, December 30, 2008" 
.SH NAME
.B nums
\- displays the most recent watched episode in each ongoing series
.SH SYNOPSIS
nums  [days]
.br
numsf [days]
.br
numss [days]
.br

.SH DESCRIPTION
Displays the most recent watched episode in each ongoing series. The default timeframe is 11 days
.br
.SH EXAMPLES
Example 1:  nums 20
.br
Shows the data for the last 20 days
.P

.SH Variations

.TP 0.5i
.B numsf
Shows finished series as well

.TP 0.5i
.B numss
Shows finished series and skipped series as well


.SH SEE ALSO 
media(7), ml(7), hista(7), ongoing(7),  shash(7)


.SH BUGS
None yet
.SH VERSION
This documentation describes
.B nums
version 200
.br
.SH AUTHOR
.br
.B Bilal Hussain
.br
