.TH ongoing 7 "R200" "Tue, December 30, 2008" 
.SH NAME
.B ongoing
\- displays series that are currently watched
.SH SYNOPSIS
ongoing
.br


.SH DESCRIPTION
Ongoing displays series that are currently watched. It shows the title current number of episodes watched and date watched  
.br
Tales of Symphonia                 3/4   208-10-19 14:51 Sun 19 Oct
.br

.SH SEE ALSO 
media(7), mal(7), hista(7),  nums(7), shash(7)


.SH BUGS
The day for some dates it always Sundays
.SH VERSION
This documentation describes
.B ongoing
version 200
.br
.SH AUTHOR
.br
.B Bilal Hussain
.br
