.TH hista 7 "R200" "Tue, December 30, 2008" 
.SH NAME
.B hista
\- set the id of a series 
.SH SYNOPSIS
set_id Series id [total]
.br

.SH DESCRIPTION
hista adds/updates a series watching history. 
.br

.SH AUGMENTS 
.B Series
\- The name of the series
.B id 
\- The id of the series
.B Total
\- The total number episodes

.SH SEE ALSO 
hista(7), hists(7), media(7), ml(7), nums(7), ongoing(7)


.SH BUGS
None yet
.SH VERSION
This documentation describes
.B hista
version 200
.br
.SH AUTHOR
.br
.B Bilal Hussain
.br
