.TH shash 7 "R200" "Tue, December 30, 2008" 
.SH NAME
.B shash
\- displays the contents of the hash
.SH SYNOPSIS
shash [hash_path]
.br


.SH DESCRIPTION
shash displays the contents of the hash e.g.
.br
fma       Fullmetal Alchemist
.br

.SH SEE ALSO 
media(7), ml(7), hista(7), nums(7), ongoing(7)


.SH BUGS
None yet
.SH VERSION
This documentation describes
.B shash
version 200
.br
.SH AUTHOR
.br
.B Bilal Hussain
.br
