.TH "main.c" 3 "18 May 2010" "Version 0.01" "Media" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'media.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPATH\fP   '/Users/bilalh/Movies/.Movie/mov/'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char const *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define PATH   '/Users/bilalh/Movies/.Movie/mov/'"
.PP
Definition at line 4 of file main.c.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char const * argv[])"
.PP
Definition at line 9 of file main.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Media from the source code.
