.TH "media.c" 3 "19 May 2010" "Version 0.01" "Media" \" -*- nroff -*-
.ad l
.nh
.SH NAME
media.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Block.h>\fP
.br
\fC#include <dirent.h>\fP
.br
\fC#include <regex.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <strings.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include 'Media.h'\fP
.br
\fC#include 'optionParser.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDIRENT\fP(value)   (*(struct dirent **) value)"
.br
.ti -1c
.RI "#define \fBVIDEO\fP   '.*\\\\.mkv|mp4|mov|ogm|avi|divx|rm|rmvb|flv|part|wmv$'"
.br
.ti -1c
.RI "#define \fBAUDIO\fP   '.*\\\\.mp3|m4a|flac|ogg|m4b|aiff|ac3|aac|wav|wmv|ape$'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmedia\fP (char *path, char **args, int argc)"
.br
.ti -1c
.RI "void \fBmplayer\fP (char **filenames, int total_length, char *prefix_args, char *postfix_args, char *filepath)"
.br
.RI "\fIFilenames should end with '', total length the length of all the strings filepath, to the directory to call mplayer from. \fP"
.ti -1c
.RI "int \fBmatch\fP (const char *string, char *pattern)"
.br
.RI "\fI1 on match, 0 on any error s \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define AUDIO   '.*\\\\.mp3|m4a|flac|ogg|m4b|aiff|ac3|aac|wav|wmv|ape$'"
.PP
Definition at line 14 of file media.c.
.SS "#define DIRENT(value)   (*(struct dirent **) value)"
.PP
Definition at line 12 of file media.c.
.SS "#define VIDEO   '.*\\\\.mkv|mp4|mov|ogm|avi|divx|rm|rmvb|flv|part|wmv$'"
.PP
Definition at line 13 of file media.c.
.SH "Function Documentation"
.PP 
.SS "int match (const char * string, char * pattern)"
.PP
1 on match, 0 on any error s Match string against the extended regular expression in pattern, treating errors as no match.
.PP
Return 1 for match, 0 for no match. 
.PP
Definition at line 81 of file media.c.
.SS "void media (char * path, char ** args, int argc)"
.PP
Definition at line 17 of file media.c.
.SS "void mplayer (char ** filenames, int total_length, char * prefix_args, char * postfix_args, char * filepath)"
.PP
Filenames should end with '', total length the length of all the strings filepath, to the directory to call mplayer from. Plays the file using mplayer. 
.PP
Definition at line 43 of file media.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Media from the source code.
